<?php
$category = $block->getEnableCategory();
$currentCategory = $block->getCurrentCategory();
if($currentCategory){
        $subcategories = $currentCategory->getChildrenCategories(); ?>
        <h2 align="center">Category list</h2>
        <?php
        foreach ($subcategories as $subcategorie) { 
            $categoryFactory = $block->getCategoryName($subcategorie->getId());
            $categoryNameshow = $categoryFactory->getName();
            $categoryUrlShow = $categoryFactory->getUrl(); 
            $categoryImageUrlShow = $categoryFactory->getCustomImage();
            $categoryIsLandingShow = $categoryFactory->getIsLanding();
            if($categoryIsLandingShow == true){
            ?>
            <div>
                <a class="category-link-show" href="<?php echo $categoryUrlShow; ?>" alt="<?php echo $categoryNameshow; ?>"
                title="<?php echo $categoryNameshow; ?>">
                    <div class="category-show-cmspage">
                        <div class="category-slide">
                            <div class="category-name-show"><?php echo $categoryNameshow; ?></div>
                            <img src="<?php echo $block->getImageUrl($categoryImageUrlShow)?>"></img>
                        </div>
                    </div>
                </a>
            </div>
            <?php
            }
        }
    ?>
    <h2 align="center">All Category list</h2>
    <?php foreach ($category as $categorydata) : ?>
    <?php
    $categoryid = $categorydata->getEntityId();
    $categoryFactory = $block->getCategoryName($categoryid);
    $categoryNameshow = $categoryFactory->getName();
    $categoryUrlShow = $categoryFactory->getUrl();
    $categoryImageUrlShow = $categoryFactory->getCustomImage();

    ?>
    <div>
        <a class="category-link-show" href="<?php echo $categoryUrlShow; ?>" alt="<?php echo $categoryNameshow; ?>"
        title="<?php echo $categoryNameshow; ?>">
            <div class="category-show-cmspage">
                <div class="category-slide">
                    <div class="category-name-show"><?php echo $categoryNameshow; ?></div>
                    
                </div>
            </div>
        </a>
    </div>
    <?php endforeach; 
    
}?>

